### ISSUE TITLE
自连接的时候，selectAs应该怎么写？

### ISSUE THREAD

**Issue by hlyang** [threefish/nutz-dao-enhance#1]
`@Table("t_primary_sys_user")
public class SysUserBean implements Serializable, Cloneable {

    @Id
    @Column(hump = true)
    private Integer userId;
    @Column(hump = true)
    private String loginName;
    @Column(hump = true)
    private String username;
    @Column(hump = true)
    private String userPwd;
    @Column(hump = true)
    private Integer isDisabled;
    @Column(hump = true)
    private Integer isSuper;
    @Column(hump = true)
    private Date lastLoginTime;
    @Column(hump = true)
    private String lastLoginIp;

    @Column(hump = true)
    private Integer isDeleted;
    @Column(hump = true)
    private Integer createUser;
    @Column(hump = true)
    private Date createDate;
    @Column(hump = true)
    private Integer updateUser;
    @Column(hump = true)
    private Date updateDate;

    @Many(field = "userId")
    private List<SysUserOrgBean> userOrgList;

    private String createUserName;
    private String updateUserName;

}`

`sysUserDao.lambdaQuery()
                .selectAs()
                .leftJoin(SysUserBean.class, SysUserBean::getCreateUser, SysUserBean::getUserId)
                .leftJoin(SysUserBean.class, SysUserBean::getUpdateUser, SysUserBean::getUserId)`

怎么才能把createUserName和updateUserName查出来

**Comment by threefish** [comment]
```
@Column
private String createUserName;
@Column
private String updateUserName;
```
这样会自动查的

**Comment by hlyang** [comment]
这两个UserName不是表里的字段，需要通过createUser这个字段自连接来查询出username然后将其赋值给createUserName和updateUserName，在自连接的时候怎么给各个表赋别名，还有selectAs怎么将字段赋别名？

**Comment by threefish** [comment]
你把期望的sql写出来吧。我给你写出lamuda语句
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月15日(星期二) 上午9:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [threefish/nutz-dao-enhance] 自连接的时候，selectAs应该怎么写？ (Issue #1)





 
这两个UserName不是表里的字段，需要通过createUser这个字段自连接来查询出username然后将其赋值给createUserName和updateUserName，在自连接的时候怎么给各个表赋别名，还有selectAs怎么将字段赋别名？

**Comment by hlyang** [comment]
是这样的：
`
select 
	su.*,
	cu.username as create_user_name,
	uu.username as update_user_name
from t_primary_sys_user su
left join t_primary_sys_user cu on cu.user_id = su.create_user
left join t_primary_sys_user uu on uu.user_id = su.update_user
`

**Comment by threefish** [comment]
你看看这个例子。

```
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Table("user")
//@IgnoreAutoDDL
public class UserDO extends BaseDO {

    @Id(auto = false)
    @AutoID
    @ColDefine(width = 9, type = ColType.INT)
    Integer id;
    @Column
    String realName;
    @Column
    Integer age;
    /**
     * 字段计算功能，可按分组进行计算
     */
    @FieldCalculation(groups = {"test"}, expression = "$ioc:fieldCalcTestService.query($this)")
    UserDO userDO;

    @FieldCalculation(groups = {"test"}, order = 1, expression = "$ioc:fieldCalcTestService.query($this)")
    UserDO userDO1;

    @FieldCalculation(groups = {"test2"}, order = 2, expression = "$this.age + $this.id")
    int test;

    @FieldCalculation(order = 1, expression = "$ioc:fieldCalcTestService.query($this)")
    UserDO userDO3;

    @Column
    private String createUserName;
    @Column
    private String updateUserName;

}
```


```
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Table("job")
public class JobDO extends BaseDO {

    @Id(auto = false)
    @AutoID
    @ColDefine(width = 9, type = ColType.INT)
    Integer id;

    @Column
    @ColDefine(width = 9, type = ColType.INT)
    Integer userId;

    @Column
    String realName;

}


```


```
  @Test
    public void test_left_join_query2() {
        List<UserDO> list = userDao.lambdaQuery()
                .selectAs(UserDO::getCreateUserName, JobDO::getRealName)
                .leftJoin(JobDO.class, UserDO::getId, JobDO::getUserId)
                .list();
        System.out.println(list);

    }

```



```
SELECT user.id,user.real_name,user.age,job.real_name as create_user_name,user.update_user_name,user.gmt_create,user.create_by FROM user LEFT JOIN job ON user.id=job.user_id 

```
